name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          npm install

      - name: Ejecutar pruebas
        run: |
          npm test
